library(rio)
library(Amelia)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(caret)
library(rpart)
library(gbm)
library(randomForest)
library(devtools)
library(woe)
library(ResourceSelection)
library(ROCR)
train <- import('data/credit-data-training.xlsx')
test <- import('data/customers-to-score.xlsx')

